# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial  # Default partition for CPU-only jobs
    cpus-per-task: 4
    mem: 16GB
    output: results/logs/slurm-%x.%A.%a.log
Dorado_baseCalling_alignment:
    partition: gpu  # Use GPU partition for this rule
    gres: "--gres=gpu:1"
    cpus-per-task: 6
    mem: 16GB
make_genome_index:
    partition: serial  # Run on normal CPU nodes
    cpus-per-task: 8
    mem: 16GB
