# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    cpus-per-task: 2
    mem:  16GB
    output: results/logs/slurm-%x.%A.%a.log
Dorado_baseCalling_alignment:
    "cpus-per-task": "6" 
    "mem": "64GB"
    "gres": "gpu:1"
    "partition": "gpu"
    "constraint": "a100|l40s"
